[package]
name = "data_struct"
version = "0.1.0"
authors = ["David Josephs <davidjosephs12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.0"
rand = "^0.5"